apiVersion: apps/v1
kind: Deployment
metadata:
  name: metricops
  namespace: nex-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metricops
  template:
    metadata:
      labels:
        app: metricops
    spec:
      serviceAccountName: nexc
      containers:
      - image: nexclipper/metric-operator:0.1.7
        imagePullPolicy: IfNotPresent 
        name: metricops
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: data
          mountPath: /redis-master-data             
      volumes:
      - name: data
        emptyDir: {}
